export const quote = [
  "Small steps every day lead to big changes.",
  "Consistency beats perfection.",
  "Build the habit, and the results will follow.",
  "One day at a time.",
  "Your future self will thank you.",
  "Progress, not perfection.",
  "A little progress is still progress.",
  "Show up for yourself every day.",
  "Habits shape the person you become.",
  "Start small. Stay consistent.",
  "Discipline turns goals into reality.",
  "Make today count.",
  "Every repetition makes the habit stronger.",
  "You don't need motivation when you have consistency.",
  "The secret is to keep going.",
  "Small actions create lasting change.",
  "Be better than yesterday.",
  "Your habits are votes for the person you want to become.",
  "Keep going, even when progress feels slow.",
  "Success is built one habit at a time.",
  "Don't break the chain.",
  "Make consistency your superpower.",
  "What you do daily matters more than what you do occasionally.",
  "Start where you are. Keep moving forward.",
  "Every day is another chance to improve.",
  "Focus on showing up, not being perfect.",
  "Your routine becomes your reality.",
  "Tiny habits can create massive results.",
  "Keep promises you make to yourself.",
  "The hardest step is the first one.",
  "Repeat good actions until they become who you are.",
  "Consistency turns effort into results.",
  "You are what you repeatedly do.",
  "Make your habits work for you.",
  "One good choice can start a great streak.",
  "Don't wait for the perfect day. Start today.",
  "Every streak starts with day one.",
  "Keep your goals close and your habits closer.",
  "Your daily actions create your tomorrow.",
  "Progress happens when you keep showing up.",
  "A better life is built from better habits.",
  "Do it today so tomorrow is easier.",
  "Stay patient. Stay consistent.",
  "The compound effect starts with one small action.",
  "Make consistency a part of your identity.",
  "You don't have to do everything. Just do something.",
  "Your next small step matters.",
  "Good habits make hard things easier.",
  "Keep going. Your streak is worth it.",
  "Today is a great day to build a better you.",
];